### PR TITLE
Update sdk image

### PR DESCRIPTION
**Pull request by bitscuit**
Need updated base image to clear vascan

### CODE REVIEW

**Comment by cheewaio** [comment]
@bitscuit you also need to delete _helpers.tpl, otherwise the install will fail.
please run `make install` to test it

**Comment by bitscuit** [comment]
@cheewaio `make install` ran without any errors. Why would it error? Because nothing from _helpers.tpl is being used?

**Comment by cheewaio** [comment]
the `make install` only deploy the operator csv and create a CR .. but you still need to verify actual installation , make sure the deployment and pods are running.
you need to run these commands to check if there any error
1. oc -n ibm-common-services describe csv ibm-helm-repo-operator.v0.0.1
2. oc -n ibm-common-services describe helmrepos default-helm-repo
3. oc -n ibm-common-services describe deployment helm-repo
4. oc -n ibm-common-services get po | grep helm-repo

**Comment by cheewaio** [comment]
closing this PR, as the changes are already merged in PR #6

**Pull request closed without merging**
